version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server/data:/app/data
    environment:
      - PORT=8080
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8080/api/v1
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped